name: Cache Update

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}-cache-update
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  checks:
    name: Checks and variables
    runs-on: ubuntu-22.04
    outputs:
      go_code_md5: ${{ steps.vars.outputs.go_code_md5 }}
      docker_md5: ${{ steps.vars.outputs.docker_md5 }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Output Variables
        id: vars
        run: |
          ./.github/scripts/variables.sh go_code_md5 >> $GITHUB_OUTPUT
          ./.github/scripts/variables.sh docker_md5 >> $GITHUB_OUTPUT
          source .github/data/version.txt
          cat $GITHUB_OUTPUT

  build-docker:
    name: Build Docker OSS
    needs: [checks]
    strategy:
      fail-fast: false
      matrix:
        image: [debian, alpine]
        platforms:
          ["linux/arm, linux/arm64, linux/amd64, linux/ppc64le, linux/s390x"]
        include:
          - image: ubi
            platforms: "linux/arm64, linux/amd64, linux/ppc64le, linux/s390x"
    uses: ./.github/workflows/build-oss.yml
    with:
      platforms: ${{ matrix.platforms }}
      image: ${{ matrix.image }}
      go-md5: ${{ needs.checks.outputs.go_code_md5 }}
      base-image-md5: ${{ needs.checks.outputs.docker_md5 }}
      authenticated: false
      tag: "edge"
      branch: ${{ github.ref }}
    permissions:
      contents: read
      actions: read
      security-events: write
      id-token: write
      packages: write
      pull-requests: write # for scout report
    secrets: inherit

  build-docker-plus:
    name: Build Docker Plus
    needs: [checks]
    strategy:
      fail-fast: false
      matrix:
        image: [debian-plus, alpine-plus, alpine-plus-fips]
        platforms: ["linux/arm64, linux/amd64"]
        target: [goreleaser, aws]
        include:
          - image: ubi-plus
            platforms: "linux/arm64, linux/amd64, linux/s390x"
            target: goreleaser
    uses: ./.github/workflows/build-plus.yml
    with:
      platforms: ${{ matrix.platforms }}
      image: ${{ matrix.image }}
      target: ${{ matrix.target }}
      go-md5: ${{ needs.checks.outputs.go_code_md5 }}
      base-image-md5: ${{ needs.checks.outputs.docker_md5 }}
      authenticated: false
      tag: "edge"
      branch: ${{ github.ref }}
    permissions:
      contents: read
      security-events: write
      id-token: write
      pull-requests: write # for scout report
    secrets: inherit

  build-docker-nap:
    name: Build Docker NAP
    needs: [checks]
    strategy:
      fail-fast: false
      matrix:
        image: [debian-plus-nap]
        platforms: ["linux/amd64"]
        target: [goreleaser, aws]
        nap_modules: [dos, waf, "waf,dos"]
        include:
          - image: ubi-9-plus-nap
            target: goreleaser
            platforms: "linux/amd64"
            nap_modules: waf
          - image: ubi-8-plus-nap
            target: goreleaser
            platforms: "linux/amd64"
            nap_modules: dos
          - image: ubi-8-plus-nap
            target: goreleaser
            platforms: "linux/amd64"
            nap_modules: "waf,dos"
          - image: ubi-9-plus-nap
            target: aws
            platforms: "linux/amd64"
            nap_modules: waf
          - image: ubi-8-plus-nap
            target: aws
            platforms: "linux/amd64"
            nap_modules: dos
          - image: ubi-8-plus-nap
            target: aws
            platforms: "linux/amd64"
            nap_modules: "waf,dos"
          - image: alpine-plus-nap-fips
            target: goreleaser
            platforms: "linux/amd64"
            nap_modules: waf
          - image: alpine-plus-nap-v5-fips
            target: goreleaser
            platforms: "linux/amd64"
            nap_modules: waf
          - image: debian-plus-nap-v5
            target: goreleaser
            platforms: "linux/amd64"
            nap_modules: waf
          - image: ubi-9-plus-nap-v5
            target: goreleaser
            platforms: "linux/amd64"
            nap_modules: waf
          - image: ubi-8-plus-nap-v5
            target: goreleaser
            platforms: "linux/amd64"
            nap_modules: waf
    uses: ./.github/workflows/build-plus.yml
    with:
      platforms: ${{ matrix.platforms }}
      image: ${{ matrix.image }}
      target: ${{ matrix.target }}
      go-md5: ${{ needs.checks.outputs.go_code_md5 }}
      base-image-md5: ${{ needs.checks.outputs.docker_md5 }}
      nap-modules: ${{ matrix.nap_modules }}
      authenticated: false
      tag: "edge"
      branch: ${{ github.ref }}
    permissions:
      contents: read
      security-events: write
      id-token: write
      pull-requests: write # for scout report
    secrets: inherit
