name: "Dependency Review"
on:
  pull_request:
    branches:
      - main
      - release-*
  merge_group:

concurrency:
  group: ${{ github.ref_name }}-deps-review
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-22.04
    permissions:
      contents: read # for actions/checkout
      pull-requests: write # for actions/dependency-review-action to post comments
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Dependency Review"
        uses: actions/dependency-review-action@4081bf99e2866ebe428fc0477b69eb4fcda7220a # v4.4.0
        with:
          config-file: "nginxinc/k8s-common/dependency-review-config.yml@main"
          base-ref: ${{ github.event.pull_request.base.sha || github.event.repository.default_branch }}
          head-ref: ${{ github.event.pull_request.base.sha || github.ref }}
