name: Patch Docker Image

on:
  workflow_call:
    inputs:
      image:
        description: The image name to patch
        required: true
        type: string
      target_image:
        description: The target name of the patched image
        required: true
        type: string
      tag:
        description: The image tag to patch
        required: true
        type: string
      target_tag:
        description: The target tag of the patched image
        required: true
        type: string
      ic_version:
        description: The IC version to label
        required: true
        type: string
      platforms:
        description: The platforms to patch
        required: true
        type: string

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  patch-image:
    name: Patch image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1

      - name: Setup QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0
        with:
          platforms: arm,arm64,ppc64le,s390x

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@f112390a2df9932162083945e46d439060d66ec2 # v2.1.4
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCR_WORKLOAD_IDENTITY }}
          service_account: ${{ secrets.GCR_SERVICE_ACCOUNT }}

      - name: Login to GCR
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Apply OS patches to Container
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 # v6.7.0
        with:
          file: build/Dockerfile
          context: "."
          target: patched
          tags: "${{ inputs.target_image }}:${{ inputs.target_tag }}"
          platforms: ${{ inputs.platforms }}
          pull: true
          push: true
          build-args: |
            IMAGE_NAME=${{ inputs.image }}:${{ inputs.tag }}
            IC_VERSION=${{ inputs.ic_version }}
