name: Release PR

on:
  workflow_dispatch:
    inputs:
      current_version:
        description: "Current version to replace"
        required: true
        default: "3.3.2"
      new_version:
        description: "Version to release"
        required: true
        default: "3.4.3"
      current_helm_version:
        description: "Current helm version to replace"
        required: true
        default: "1.0.2"
      new_helm_version:
        description: "Helm version to release"
        required: true
        default: "1.1.3"
      k8s_versions:
        description: "Kubernetes versions this release has been tested on"
        required: true
        default: "x.xx-x.xx"
      release_date:
        description: "Date for this release"
        required: true
        default: "%d %b %Y"

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Branch
        id: branch
        run: |
          version=${{ github.event.inputs.new_version }}
          version=${version%.*}
          echo "branch=release-$version" >> $GITHUB_OUTPUT

      - name: Checkout Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ steps.branch.outputs.branch }}
          token: ${{ secrets.NGINX_PAT }}

      - name: Replace
        run: |
          .github/scripts/release-version-update.sh ${{ github.event.inputs.current_version }} ${{ github.event.inputs.current_helm_version }} ${{ github.event.inputs.new_version }} ${{ github.event.inputs.new_helm_version }}
          .github/scripts/release-notes-update.sh ${{ github.event.inputs.new_version }} ${{ github.event.inputs.new_helm_version }} "${{ github.event.inputs.k8s_versions }}" "${{ github.event.inputs.release_date }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
        with:
          token: ${{ secrets.NGINX_PAT }}
          commit-message: Release ${{ github.event.inputs.new_version }}
          title: Release ${{ github.event.inputs.new_version }}
          branch: docs/release-${{ github.event.inputs.new_version }}
          author: nginx-bot <integrations@nginx.com>
          body: |
            This automated PR updates the docs for ${{ github.event.inputs.new_version }} release.
