name: "Retag Dev Images"

on:
  workflow_dispatch:
    inputs:
      source_tag:
        required: true
        type: string
      target_tag:
        required: true
        type: string
      dry_run:
        type: boolean
        default: false
  workflow_call:
    inputs:
      source_tag:
        required: true
        type: string
      target_tag:
        required: true
        type: string
      dry_run:
        type: boolean
        default: false

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  copy-to-gcr-dev-registry:
    name: Re-tag images in GCR Dev Registry
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Authenticate to Google Cloud
        id: gcr-auth
        uses: google-github-actions/auth@62cf5bd3e4211a0a0b51f2c6d6a37129d828611d # v2.1.5
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCR_WORKLOAD_IDENTITY }}
          service_account: ${{ secrets.GCR_SERVICE_ACCOUNT }}

      - name: Login to GCR
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.gcr-auth.outputs.access_token }}

      - name: Retag images
        run: |
          export CONFIG_PATH=.github/config/config-gcr-retag
          export SOURCE_TAG=${{ inputs.source_tag }}
          export TARGET_TAG=${{ inputs.target_tag }}
          if ${{ inputs.dry_run }}; then
            export DRY_RUN=true
          fi
          .github/scripts/copy-images.sh
