name: "Bump the IC & Helm chart version"

on:
  workflow_dispatch:
    inputs:
      source_branch:
        required: true
        type: string
        default: "main"
      ic_version:
        required: true
        type: string
        default: "0.0.0"
      helm_chart_version:
        required: true
        type: string
        default: "0.0.0"

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  version-bump:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.source_branch }}

      - name: Replace Versions
        run: |
          yq -i e '.version = env(CHART_VERSION) | .appVersion = env(IC_VERSION)' charts/nginx-ingress/Chart.yaml
          cat charts/nginx-ingress/Chart.yaml
          cat > .github/data/version.txt << EOF
          IC_VERSION=${IC_VERSION}
          HELM_CHART_VERSION=${CHART_VERSION}
          EOF
          cat .github/data/version.txt
        env:
          IC_VERSION: ${{ inputs.ic_version }}
          CHART_VERSION: ${{ inputs.helm_chart_version }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f # v7.0.6
        with:
          token: ${{ secrets.NGINX_PAT }}
          commit-message: Version Bump for ${{ github.event.inputs.ic_version }}
          title: Version Bump for ${{ github.event.inputs.ic_version }}
          branch: chore/version-bump-${{ github.event.inputs.ic_version }}
          author: nginx-bot <integrations@nginx.com>
          labels: chore
          body: |
            This automated PR updates the NIC & Helm chart versions for the upcoming ${{ github.event.inputs.ic_version }} release.
